### ISSUE TITLE
Create/Update/Delete User and assing Roles

### ISSUE THREAD

**Issue by nkev** [joelnb/sofa#10]
Thanks for this great project.
I could find how to create/update/delete Users and assign Roles. 
Is there a way to do that?

**Comment by joelnb** [comment]
I am glad you are finding some use for this project.

There are some utility methods to make life easier when querying current users:
- [Connection.User](https://pkg.go.dev/github.com/joelnb/sofa?tab=doc#Connection.User)
- [Connection.Users](https://pkg.go.dev/github.com/joelnb/sofa?tab=doc#Connection.Users)

There are not currently any such functions for create/update/delete of users.

I tried to create you an example using the current API and I came up with this:

```go
package main

import (
	"fmt"
	"time"

	"github.com/joelnb/sofa"
)

func main() {
	conn, err := sofa.NewConnection("http://localhost:5984", 10*time.Second, sofa.NullAuthenticator())
	if err != nil {
		panic(err)
	}

	// Open the previously-created database
	db := conn.Database("_users")

	user := sofa.UserDocument{
		DocumentMetadata: sofa.DocumentMetadata{
			ID: "org.couchdb.user:nkev",
		},
		Name:     "nkev",
		Password: "nkev",
		Roles:    []string{"reporter"},
		TheType:  "user",
	}

	rev, err := db.Put(&user)
	if err != nil {
		panic(err)
	}

	// Show the revision which has been created
	fmt.Println(rev)

	// Retrieve the document which was created
	realUser, err := conn.User("org.couchdb.user:nkev", rev)
	if err != nil {
		panic(err)
	}

	delrev, err := db.Delete(&realUser)
	if err != nil {
		panic(err)
	}

	fmt.Println(delrev)
}
```

This works but I feel like it's fairly ugly and it made me realise that there is a problem with the current API - if you specify an empty list of roles the creation fails (due to the `omitempty` not including the field at all).

Rather than simply fix that I had a go at creating an API which I'm happier with (see [this branch](https://github.com/joelnb/sofa/tree/new-users-api)) and came up with this example using that new API:

```go
package main

import (
	"fmt"
	"time"

	"github.com/joelnb/sofa"
)

func main() {
	conn, err := sofa.NewConnection("http://localhost:5984", 10*time.Second, sofa.NullAuthenticator())
	if err != nil {
		panic(err)
	}

	user := sofa.UserDocument{
		Name:     "nkev",
		Password: "nkev",
		Roles:    []string{},
		TheType:  "user",
	}

	rev, err := conn.CreateUser(user)
	if err != nil {
		panic(err)
	}

	// Show the revision which has been created
	fmt.Println(rev)

	// Retrieve the document which was created
	realUser, err := conn.User("nkev", rev)
	if err != nil {
		panic(err)
	}

	// Show the whole retrieved user
	fmt.Printf("%+v\n", realUser)

	// Modify the roles for the user
	realUser.Roles = []string{"issue_creator"}

	// Save the modified user
	updateRev, err := conn.UpdateUser(realUser)
	if err != nil {
		panic(err)
	}

	// Ensure the document has the latest revision so the delete works
	realUser.DocumentMetadata.Rev = updateRev

	// Delete the user
	delrev, err := conn.DeleteUser(realUser)
	if err != nil {
		panic(err)
	}

	fmt.Println(delrev)
}
```

I'm not sure I'm 100% happy with this new API but I feel like it's a big improvement over the current state (and this new example also includes an update which I did not cover in the first example).

What do you think about this? I will probably think further on it but any input is always appreciated.

**Comment by nkev** [comment]
That's great! Thank you. Perhaps putting these samples into an /examples folder will make it easy for others to discover. 

If you create outstanding issues that you need help with, I'd be glad to contribute.

**Comment by joelnb** [comment]
> Perhaps putting these samples into an /examples folder will make it easy for others to discover.

Yes I like this idea. I found [this blog post](https://blog.golang.org/examples) and I think this is a good solution because it means the examples will be kept up to date as they are part of the tests.

I've pushed a version which includes that & the small fix for the issue I mentioned with `omitempty`.

I've also created a merge request for the new API I showed above: https://github.com/joelnb/sofa/pull/11. If I can't think of any improvements I'll write a test or 2 and then go ahead and merge it.

**Comment by nkev** [comment]
Awesome!

**Comment by joelnb** [comment]
I merged the PR I created for the new API I showed here: https://github.com/joelnb/sofa/pull/11

I did make a couple of small changes but I updated the example (and this should stay up to date because it is run as part of the tests now). You can see the examples here (it's not yet got the 0.2.0 I tagged but shouldn't be too long): https://pkg.go.dev/github.com/joelnb/sofa?tab=doc
